[package]
name = "qromp/els-dependencies"
version = "0.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.15.1"
Net = "vorlias/net@3.0.4"
Promise = "evaera/promise@4.0.0"
React = "core-packages/react@17.0.1-rc.16"
RoactCompat = "core-packages/roact-compat@17.0.1-rc.16.1"
RoactRodux = "grilme99/roact-rodux@0.5.2"
Rodux = "roblox/rodux@4.0.0-rc.0"
Sift = "csqrl/sift@0.0.5"
Signal = "chipioindustries/signal@1.2.0"
t = "osyrisrblx/t@3.0.0"